function save_csv(csvFile, filename, bloco, iluminacao, AprilTag, coord_real, coord_est, timestamp, metodo)

    % Criar tabela com uma linha
    T = table( ...
        string(filename), bloco, string(iluminacao), string(AprilTag),...
        coord_real(1), coord_real(2), coord_real(3), ...
        coord_est(1), coord_est(2), coord_est(3), ...
        timestamp, string(metodo), ...
        'VariableNames', ...
        {'Foto', 'Bloco', 'Iluminacao','AprilTag','Real_X','Real_Y','Real_Z', ...
         'Est_X','Est_Y','Est_Z','DataHora', 'Metodo'});

    % Se o ficheiro já existir → append
    if isfile(csvFile)
        writetable(T, csvFile, 'WriteMode','append');
    else
        writetable(T, csvFile);
    end

end